# Julia
Julia je novi jezik, nastao 2012. godine.
Julia je dinamički jezik koji se može kompajlirati te dobiti vrlo dobre performanse (često u rangu C-a).
Ima sličnosti s Pythonom, ali i s Lispom. Prvenstvena namjena mu je znanstveno računanje, ali dizajniran je tako da i u domeni nespecijaliziranih programskih jezika može naći svoje mjesto. 

In [1]:
VERSION

v"0.4.1"

In [2]:
f(x, y) = 1 + 2x*y^2

f (generic function with 1 method)

In [3]:
f(1,4)

33

In [4]:
α=3

3

In [5]:
println("α=", α)

α=3

In [6]:
μ=3
println("Sinus od $μ je $(sin(μ))")

In [7]:
10^19

-8446744073709551616

In [8]:
BigInt(10)^19

10000000000000000000


Sinus od 3 je 0.1411200080598672


In [9]:
a = Int8(1)
b = Int8(2)
a + b

3

In [10]:
typeof(ans)

Int8

In [11]:
typemax(Int64)

9223372036854775807

In [12]:
c = 1+3.5im

1.0 + 3.5im

In [13]:
c^2

-11.25 + 7.0im

In [14]:
c.re, c.im

(1.0,3.5)

In [15]:
3//4

3//4

In [16]:
typeof(ans)

Rational{Int64}

In [17]:
//(3, 4)

3//4

In [18]:
//

// (generic function with 8 methods)

In [19]:
methods(//)

# 8 methods for generic function "//":
//(n::Integer, d::Integer) at rational.jl:22
//(x::Rational{T<:Integer}, y::Integer) at rational.jl:25
//(x::Integer, y::Rational{T<:Integer}) at rational.jl:29
//(x::Rational{T<:Integer}, y::Rational{T<:Integer}) at rational.jl:33
//(x::Complex{T<:Real}, y::Real) at rational.jl:38
//{Ra<:Rational{T<:Integer},Rb<:Rational{T<:Integer}}(x::Complex{Ra<:Rational{T<:Integer}}, y::Complex{Rb<:Rational{T<:Integer}}) at rational.jl:45
//(x::Number, y::Complex{T<:Real}) at rational.jl:40
//(X::AbstractArray{T,N}, y::Number) at rational.jl:50

In [20]:
l = [3, 4, 5]

3-element Array{Int64,1}:
 3
 4
 5

In [21]:
l[1]

3

In [22]:
l[1:2]

2-element Array{Int64,1}:
 3
 4

In [23]:
l[2:end]

2-element Array{Int64,1}:
 4
 5

In [24]:
l[1:end-1]

2-element Array{Int64,1}:
 3
 4

In [25]:
a = [1.1, 2.2, 3.3]
b = [4.4, 5.5, 6.6]

3-element Array{Float64,1}:
 4.4
 5.5
 6.6

In [26]:
dot(a,b)

38.72

In [27]:
a*b

LoadError: LoadError: MethodError: `*` has no method matching *(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
  *{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(!Matched::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, ::Union{DenseArray{S,1},SubArray{S,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  *{TA,TB}(!Matched::Base.LinAlg.AbstractTriangular{TA,S<:AbstractArray{T,2}}, ::Union{DenseArray{TB,1},DenseArray{TB,2},SubArray{TB,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD},SubArray{TB,2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  ...
while loading In[27], in expression starting on line 1

In [28]:
a.*b

3-element Array{Float64,1}:
  4.84
 12.1 
 21.78

In [29]:
norm(a)

4.115823125451335

In [30]:
a⋅b

38.72

In [31]:
a×b

3-element Array{Float64,1}:
 -3.63
  7.26
 -3.63

In [32]:
Ψ = norm

norm (generic function with 9 methods)

In [33]:
Ψ(a)

4.115823125451335

In [34]:
?norm

search: 

```rst
..  norm(A, [p])

Compute the ``p``-norm of a vector or the operator norm of a matrix ``A``, defaulting to the ``p=2``-norm.

For vectors, ``p`` can assume any numeric value (even though not all values produce a mathematically valid vector norm). In particular, ``norm(A, Inf)`` returns the largest value in ``abs(A)``, whereas ``norm(A, -Inf)`` returns the smallest.

For matrices, the matrix norm induced by the vector ``p``-norm is used, where valid values of ``p`` are ``1``, ``2``, or ``Inf``. (Note that for sparse matrices, ``p=2`` is currently not implemented.) Use :func:`vecnorm` to compute the Frobenius norm.
```


In [35]:
suma = 0
for i = 1:10
    suma += i
end
println("Suma je $suma")

norm normpath normalize_string vecnorm issubnormal UniformScaling

Suma je 55


In [36]:
kvadrati = [i^2 for i in [1:2:10; 7]]

6-element Array{Any,1}:
  1
  9
 25
 49
 81
 49

In [37]:
M = [2 1; 1 1]

2x2 Array{Int64,2}:
 2  1
 1  1

In [38]:
M[:,1]

2-element Array{Int64,1}:
 2
 1

In [39]:
rand()

0.08433401828782672

In [40]:
v = [1, 2]

2-element Array{Int64,1}:
 1
 2

In [41]:
M*v

2-element Array{Int64,1}:
 4
 3

In [42]:
dot(v,v)

5

In [43]:
M = rand(100, 100)

100x100 Array{Float64,2}:
 0.220858    0.88376    0.269541    …  0.658997   0.220733    0.555561 
 0.406221    0.0956693  0.226183       0.23468    0.0524241   0.579552 
 0.405399    0.420104   0.677982       0.557283   0.560016    0.0643022
 0.368826    0.510526   0.117388       0.578252   0.481915    0.959236 
 0.497433    0.443177   0.659915       0.881005   0.370444    0.0619745
 0.193415    0.803661   0.818881    …  0.36704    0.360221    0.606479 
 0.97618     0.39269    0.619167       0.584681   0.199493    0.391931 
 0.0798537   0.521397   0.392636       0.152159   0.285777    0.586661 
 0.939772    0.781614   0.00780299     0.478098   0.927307    0.0226647
 0.959618    0.846427   0.207888       0.588996   0.720221    0.85664  
 0.435697    0.411868   0.113955    …  0.0439245  0.418131    0.249366 
 0.991886    0.0399136  0.662217       0.556256   0.534784    0.843859 
 0.177179    0.887014   0.146172       0.887471   0.198925    0.246988 
 ⋮                                  ⋱ 

In [44]:
@time lamb, vv = eig(M)

(Complex{Float64}[49.9114+0.0im,-3.28857+0.0im,-1.11507+2.73467im,-1.11507-2.73467im,2.24025+1.85135im,2.24025-1.85135im,0.326204+2.8559im,0.326204-2.8559im,2.76996+0.0im,2.72904+0.80452im  …  0.468392+0.856219im,0.468392-0.856219im,0.332954+0.614922im,0.332954-0.614922im,-0.472013+0.19183im,-0.472013-0.19183im,0.102945+0.396573im,0.102945-0.396573im,-0.690244+0.0im,0.0303506+0.0im],
100x100 Array{Complex{Float64},2}:
  -0.108012+0.0im   0.0671103+0.0im  …   -0.0329898+0.0im  -0.0860527+0.0im
 -0.0959131+0.0im   -0.100793+0.0im      -0.0523681+0.0im   -0.179368+0.0im
 -0.0997671+0.0im   0.0676716+0.0im       -0.146404+0.0im   0.0558498+0.0im
 -0.0958394+0.0im   0.0362543+0.0im        0.130139+0.0im   0.0792805+0.0im
 -0.0975858+0.0im    0.112506+0.0im       -0.251938+0.0im   -0.108042+0.0im
  -0.101765+0.0im    0.116531+0.0im  …   -0.0475842+0.0im    0.029516+0.0im
  -0.106032+0.0im    0.176498+0.0im      -0.0699838+0.0im    0.216656+0.0im
 -0.0838082+0.0im   -0.127607+0.0im        0.1

In [45]:
lu(M)

0.692729 seconds (523.77 k allocations: 24.189 MB, 1.79% gc time)


(
100x100 Array{Float64,2}:
 1.0         0.0         0.0        …   0.0        0.0       0.0       0.0
 0.485822    1.0         0.0            0.0        0.0       0.0       0.0
 0.94746     0.804693    1.0            0.0        0.0       0.0       0.0
 0.836357    0.0350559  -0.325509       0.0        0.0       0.0       0.0
 0.0386356   0.471818   -0.370179       0.0        0.0       0.0       0.0
 0.967467    0.873949    0.869919   …   0.0        0.0       0.0       0.0
 0.212538    0.342977   -0.25266        0.0        0.0       0.0       0.0
 0.269071    0.69633    -0.29435        0.0        0.0       0.0       0.0
 0.298818    0.62283     0.128163       0.0        0.0       0.0       0.0
 0.29262     0.537404    0.291404       0.0        0.0       0.0       0.0
 0.859334    0.301921   -0.203452   …   0.0        0.0       0.0       0.0
 0.774017    0.879167    0.882789       0.0        0.0       0.0       0.0
 0.934564    0.856854    0.721019       0.0        0.0       0.0       0

In [46]:
norm(M)

50.1161053500091

In [47]:
function normakvadrata(M)
    norm(M^2)
end

normakvadrata (generic function with 1 method)

In [48]:
normakvadrata(M)

2501.4933355814755

In [49]:
Base.(:(+))(s1::AbstractString, s2::AbstractString) = string(s1, s2)

+ (generic function with 172 methods)

In [50]:
"Prvi" + " drugi"

"Prvi drugi"

In [51]:
"Vrijednost od x je " + 3

LoadError: LoadError: MethodError: `+` has no method matching +(::ASCIIString, ::Int64)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...)
  +(!Matched::Int64, ::Int64)
  +(!Matched::Complex{Bool}, ::Real)
  ...
while loading In[51], in expression starting on line 1

In [52]:
Base.(:(+))(s::AbstractString, x::Number) = s + "$(2x)"

+ (generic function with 173 methods)

In [53]:
"Vrijednost od x je " + 3

"Vrijednost od x je 6"

In [54]:
immutable Vector2D
    x::Float64
    y::Float64
end

In [55]:
v = Vector2D(3, 4);
w = Vector2D(5, 6);

In [56]:
v + w

LoadError: LoadError: MethodError: `+` has no method matching +(::Vector2D, ::Vector2D)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...)
while loading In[56], in expression starting on line 1

In [57]:
Base.(:(+))(v::Vector2D, w::Vector2D) = Vector2D(v.x+w.x, v.y+w.y)

+ (generic function with 174 methods)

In [58]:
v+w

Vector2D(8.0,10.0)

In [59]:
Base.(:(*))(v::Vector2D, α::Number) = Vector2D(v.x*α, v.y*α)
Base.(:(*))(α::Number, v::Vector2D) = Vector2D(v.x*α, v.y*α)

* (generic function with 140 methods)

In [60]:
v * 3.5

Vector2D(10.5,14.0)

In [61]:
3.5 * v

Vector2D(10.5,14.0)

In [62]:
methods(+)

# 174 methods for generic function "+":
+(x::Bool) at bool.jl:33
+(x::Bool, y::Bool) at bool.jl:36
+(y::AbstractFloat, x::Bool) at bool.jl:46
+(x::Int64, y::Int64) at int.jl:8
+(x::Int8, y::Int8) at int.jl:16
+(x::UInt8, y::UInt8) at int.jl:16
+(x::Int16, y::Int16) at int.jl:16
+(x::UInt16, y::UInt16) at int.jl:16
+(x::Int32, y::Int32) at int.jl:16
+(x::UInt32, y::UInt32) at int.jl:16
+(x::UInt64, y::UInt64) at int.jl:16
+(x::Int128, y::Int128) at int.jl:16
+(x::UInt128, y::UInt128) at int.jl:16
+(x::Integer, y::Ptr{T}) at pointer.jl:77
+(x::Float32, y::Float32) at float.jl:203
+(x::Float64, y::Float64) at float.jl:204
+(z::Complex{T<:Real}, w::Complex{T<:Real}) at complex.jl:111
+(x::Bool, z::Complex{Bool}) at complex.jl:118
+(z::Complex{Bool}, x::Bool) at complex.jl:119
+(x::Bool, z::Complex{T<:Real}) at complex.jl:125
+(z::Complex{T<:Real}, x::Bool) at complex.jl:126
+(x::Real, z::Complex{Bool}) at complex.jl:132
+(z::Complex{Bool}, x::Real) at complex.jl:133
+(x::Real, z::Complex{T<:Real}) at complex.jl:144
+(z::Complex{T<:Real}, x::Real) at complex.jl:145
+(x::Rational{T<:Integer}, y::Rational{T<:Integer}) at rational.jl:179
+(x::Bool, A::AbstractArray{Bool,N}) at arraymath.jl:136
+(x::Integer, y::Char) at char.jl:43
+(a::Float16, b::Float16) at float16.jl:136
+(x::BigInt, y::BigInt) at gmp.jl:256
+(a::BigInt, b::BigInt, c::BigInt) at gmp.jl:279
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt) at gmp.jl:285
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) at gmp.jl:292
+(x::BigInt, c::Union{UInt16,UInt32,UInt64,UInt8}) at gmp.jl:304
+(c::Union{UInt16,UInt32,UInt64,UInt8}, x::BigInt) at gmp.jl:308
+(x::BigInt, c::Union{Int16,Int32,Int64,Int8}) at gmp.jl:320
+(c::Union{Int16,Int32,Int64,Int8}, x::BigInt) at gmp.jl:321
+(x::BigFloat, y::BigFloat) at mpfr.jl:208
+(x::BigFloat, c::Union{UInt16,UInt32,UInt64,UInt8}) at mpfr.jl:215
+(c::Union{UInt16,UInt32,UInt64,UInt8}, x::BigFloat) at mpfr.jl:219
+(x::BigFloat, c::Union{Int16,Int32,Int64,Int8}) at mpfr.jl:223
+(c::Union{Int16,Int32,Int64,Int8}, x::BigFloat) at mpfr.jl:227
+(x::BigFloat, c::Union{Float16,Float32,Float64}) at mpfr.jl:231
+(c::Union{Float16,Float32,Float64}, x::BigFloat) at mpfr.jl:235
+(x::BigFloat, c::BigInt) at mpfr.jl:239
+(c::BigInt, x::BigFloat) at mpfr.jl:243
+(a::BigFloat, b::BigFloat, c::BigFloat) at mpfr.jl:379
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) at mpfr.jl:385
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) at mpfr.jl:392
+(x::Irrational{sym}, y::Irrational{sym}) at irrationals.jl:72
+(x::Number) at operators.jl:73
+{T<:Number}(x::T<:Number, y::T<:Number) at promotion.jl:211
+{T<:AbstractFloat}(x::Bool, y::T<:AbstractFloat) at bool.jl:43
+(x::Number, y::Number) at promotion.jl:167
+(r1::OrdinalRange{T,S}, r2::OrdinalRange{T,S}) at operators.jl:330
+{T<:AbstractFloat}(r1::FloatRange{T<:AbstractFloat}, r2::FloatRange{T<:AbstractFloat}) at operators.jl:337
+{T<:AbstractFloat}(r1::LinSpace{T<:AbstractFloat}, r2::LinSpace{T<:AbstractFloat}) at operators.jl:356
+(r1::Union{FloatRange{T<:AbstractFloat},LinSpace{T<:AbstractFloat},OrdinalRange{T,S}}, r2::Union{FloatRange{T<:AbstractFloat},LinSpace{T<:AbstractFloat},OrdinalRange{T,S}}) at operators.jl:369
+(x::Ptr{T}, y::Integer) at pointer.jl:75
+{S,T}(A::Range{S}, B::Range{T}) at arraymath.jl:69
+{S,T}(A::Range{S}, B::AbstractArray{T,N}) at arraymath.jl:87
+(A::BitArray{N}, B::BitArray{N}) at bitarray.jl:845
+{T}(B::BitArray{2}, J::UniformScaling{T}) at linalg/uniformscaling.jl:28
+(A::Array{T,2}, B::Diagonal{T}) at linalg/special.jl:122
+(A::Array{T,2}, B::Bidiagonal{T}) at linalg/special.jl:122
+(A::Array{T,2}, B::Tridiagonal{T}) at linalg/special.jl:122
+(A::Array{T,2}, B::SymTridiagonal{T}) at linalg/special.jl:131
+(A::Array{T,2}, B::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}) at linalg/special.jl:159
+(A::Array{T,N}, B::SparseMatrixCSC{Tv,Ti<:Integer}) at sparse/sparsematrix.jl:1019
+{P<:Union{Base.Dates.CompoundPeriod,Base.Dates.Period}}(x::Union{De

In [63]:
function sum1(N::Int)
    total = 0
    
    for i in 1:N
        total += i/2
    end
    
    total
end

function sum2(N::Int)
    total = 0.0
    
    for i in 1:N
        total += i/2
    end
    
    total
end

sum2 (generic function with 1 method)

In [64]:
sum1(10), sum2(10)

(27.5,27.5)

In [65]:
N = 10000000

@time sum1(N)
@time sum2(N)

2.50000025e13

In [66]:
code_typed(sum2, (Int,))

1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:N], Any[Any[Any[:N,Int64,0],Any[:total,Float64,2],Any[symbol("#s41"),Int64,2],Any[:i,Int64,18]],Any[],Any[UnitRange{Int64},Tuple{Int64,Int64},Int64,Int64],Any[]], :(begin  # In[63], line 12:
        total = 0.0 # In[63], line 14:
        GenSym(0) = $(Expr(:new, UnitRange{Int64}, 1, :(((top(getfield))(Base.Intrinsics,:select_value)::I)((Base.sle_int)(1,N::Int64)::Bool,N::Int64,(Base.box)(Int64,(Base.sub_int)(1,1)))::Int64)))
        #s41 = (top(getfield))(GenSym(0),:start)::Int64
        unless (Base.box)(Base.Bool,(Base.not_int)(#s41::Int64 === (Base.box)(Base.Int,(Base.add_int)((top(getfield))(GenSym(0),:stop)::Int64,1))::Bool)) goto 1
        2: 
        GenSym(2) = #s41::Int64
        GenSym(3) = (Base.box)(Base.Int,(Base.add_int)(#s41::Int64,1))
        i = GenSym(2)
        #s41 = GenSym(3) # In[63], line 15:
        total = (Base.box)(Base.Float64,(Base.add_float)(total::Float64,(Base.box)(Base.Float64,(Base.div_float)((Base.box)(F

0.297885 seconds (20.00 M allocations: 305.176 MB, 12.55% gc time)
  0.011619 seconds (5 allocations: 176 bytes)


In [67]:
code_llvm(sum2, (Int, ))


define double @julia_sum2_22582(i64) {
top:
  %1 = icmp sgt i64 %0, 0
  %2 = select i1 %1, i64 %0, i64 0
  %3 = icmp eq i64 %2, 0
  br i1 %3, label %L3, label %L

L:                                                ; preds = %L, %top
  %total.0 = phi double [ %7, %L ], [ 0.000000e+00, %top ]
  %"#s41.0" = phi i64 [ %4, %L ], [ 1, %top ]
  %4 = add i64 %"#s41.0", 1
  %5 = sitofp i64 %"#s41.0" to double
  %6 = fmul double %5, 5.000000e-01
  %7 = fadd double %total.0, %6
  %8 = icmp eq i64 %"#s41.0", %2
  br i1 %8, label %L3, label %L

L3:                                               ; preds = %L, %top
  %total.1 = phi double [ 0.000000e+00, %top ], [ %7, %L ]
  ret double %total.1
}


In [75]:
code_native(sum2, (Int,))

	.text
Filename: In[63]
Source line: 14
	pushq	%rbp
	movq	%rsp, %rbp
	xorl	%eax, %eax
	testq	%rdi, %rdi
	movl	$0, %ecx
Source line: 14
	cmovnsq	%rdi, %rcx
	xorps	%xmm0, %xmm0
	testq	%rcx, %rcx
	je	L87
	testq	%rdi, %rdi
	cmovnsq	%rdi, %rax
	movl	$1, %ecx
	xorps	%xmm0, %xmm0
	movabsq	$139674202336752, %rdx  # imm = 0x7F086F36EDF0
	movsd	(%rdx), %xmm1
Source line: 15
L59:	xorps	%xmm2, %xmm2
	cvtsi2sdq	%rcx, %xmm2
	mulsd	%xmm1, %xmm2
	addsd	%xmm2, %xmm0
Source line: 14
	incq	%rcx
Source line: 15
	decq	%rax
	jne	L59
Source line: 18
L87:	popq	%rbp
	ret


In [69]:
# prvi put sam instalirao PyCall sa sljedećim naredbama
#Pkg.update()
#Pkg.add("PyCall")
using PyCall

In [76]:
@pyimport numpy.random as nprandom
nprandom.rand(3,4)

3x4 Array{Float64,2}:
 0.890654  0.0456051  0.662302  0.227281
 0.993089  0.555402   0.588366  0.739059
 0.891837  0.6437     0.931653  0.483991

In [71]:
objective = x -> cos(x) - x #ekvivalent lambda funkcijama u Pythonu

(anonymous function)

In [72]:
@pyimport scipy.optimize as so
so.newton(objective, 1)

0.7390851332151607

In [73]:
t = ccall( (:clock, "libc"), Int32, ())

19520277

In [74]:
function es(n::Int64)
    l = ones(Bool, n)
    l[1] = false
    for i in 2:int64(sqrt(n))
        if l[i]
            for j in (i*i):i:n
                l[j] = false
            end
        end
    end
    return filter(x -> l[x],1:n)
end

es (generic function with 1 method)