# Julia
Julia je novi jezik, nastao 2012. godine.
Julia je dinamički jezik koji se može kompajlirati te dobiti vrlo dobre performanse (često u rangu C-a).
Ima sličnosti s Pythonom, ali i s Lispom. Prvenstvena namjena mu je znanstveno računanje, ali dizajniran je tako da i u domeni nespecijaliziranih programskih jezika može naći svoje mjesto. 

In [1]:
f(x, y) = 1 + 2x*y^2

f (generic function with 1 method)

In [2]:
f(1,4)

33

In [3]:
α=3

3

In [4]:
println("α=", α)

α=3


In [5]:
μ=3
println("Sinus od $μ je $(sin(μ))")

Sinus od 3 je 0.1411200080598672


In [6]:
10^19

-8446744073709551616

In [7]:
BigInt(10)^19

10000000000000000000

In [8]:
a = int8(1)
b = int8(2)
a + b

3

In [9]:
typeof(ans)

Int64

In [10]:
typemax(Int64)

9223372036854775807

In [11]:
c = 1+3.5im

1.0 + 3.5im

In [12]:
c^2

-11.25 + 7.0im

In [13]:
c.re, c.im

(1.0,3.5)

In [14]:
3//4

3//4

In [15]:
typeof(ans)

Rational{Int64} (constructor with 1 method)

In [16]:
//(3, 4)

3//4

In [17]:
//

// (generic function with 8 methods)

In [49]:
methods(//)

# 8 methods for generic function "//":
//(n::Integer,d::Integer) at rational.jl:15
//(x::Rational{T<:Integer},y::Integer) at rational.jl:16
//(x::Integer,y::Rational{T<:Integer}) at rational.jl:17
//(x::Rational{T<:Integer},y::Rational{T<:Integer}) at rational.jl:18
//(x::Complex{T<:Real},y::Real) at rational.jl:19
//(x::Real,y::Complex{T<:Real}) at rational.jl:20
//(x::Complex{T<:Real},y::Complex{T<:Real}) at rational.jl:23
//(X::AbstractArray{T,N},y::Number) at rational.jl:28

In [18]:
l = [3, 4, 5]

3-element Array{Int64,1}:
 3
 4
 5

In [19]:
l[1]

3

In [20]:
l[1:2]

2-element Array{Int64,1}:
 3
 4

In [21]:
l[2:end]

2-element Array{Int64,1}:
 4
 5

In [22]:
l[1:end-1]

2-element Array{Int64,1}:
 3
 4

In [23]:
a = [1.1, 2.2, 3.3]
b = [4.4, 5.5, 6.6]

3-element Array{Float64,1}:
 4.4
 5.5
 6.6

In [24]:
dot(a,b)

38.72

In [25]:
a*b

LoadError: `*` has no method matching *(::Array{Float64,1}, ::Array{Float64,1})
while loading In[25], in expression starting on line 1

In [26]:
a.*b

3-element Array{Float64,1}:
  4.84
 12.1 
 21.78

In [27]:
norm(a)

4.115823125451335

In [28]:
a⋅b

38.72

In [29]:
a×b

3-element Array{Float64,1}:
 -3.63
  7.26
 -3.63

In [30]:
Ψ = norm

norm (generic function with 15 methods)

In [31]:
Ψ(a)

4.115823125451335

In [32]:
help("norm")

INFO: Loading help data...


Base.norm(A[, p])

   Compute the "p"-norm of a vector or the operator norm of a matrix
   "A", defaulting to the "p=2"-norm.

   For vectors, "p" can assume any numeric value (even though not
   all values produce a mathematically valid vector norm). In
   particular, "norm(A, Inf)" returns the largest value in
   "abs(A)", whereas "norm(A, -Inf)" returns the smallest.

   For matrices, valid values of "p" are "1", "2", or "Inf".
   (Note that for sparse matrices, "p=2" is currently not
   implemented.) Use "vecnorm()" to compute the Frobenius norm.


In [33]:
suma = 0
for i = 1:10
    suma += i
end
println("Suma je $suma")

Suma je 55


In [34]:
kvadrati = [i^2 for i in [1:2:10, 7]]

6-element Array{Any,1}:
  1
  9
 25
 49
 81
 49

In [35]:
M = [2 1; 1 1]

2x2 Array{Int64,2}:
 2  1
 1  1

In [36]:
M[:,1]

2-element Array{Int64,1}:
 2
 1

In [37]:
rand()

0.72322178614349

In [38]:
v = [1, 2]

2-element Array{Int64,1}:
 1
 2

In [39]:
M*v

2-element Array{Int64,1}:
 4
 3

In [40]:
dot(v,v)

5

In [41]:
M = rand(100, 100)

100x100 Array{Float64,2}:
 0.498759   0.274196   0.589413   …  0.153458   0.619451    0.27949  
 0.719717   0.826101   0.427449      0.0244593  0.287578    0.803427 
 0.46495    0.666569   0.445141      0.394023   0.552363    0.845297 
 0.62161    0.546013   0.053935      0.0037514  0.839461    0.0261154
 0.679678   0.233125   0.926472      0.702835   0.723128    0.33435  
 0.871057   0.454973   0.973416   …  0.542395   0.195786    0.326218 
 0.772791   0.595738   0.165141      0.973998   0.93593     0.468537 
 0.190604   0.659578   0.347895      0.401351   0.00163175  0.168997 
 0.402977   0.633266   0.407776      0.0575996  0.0180004   0.984783 
 0.799693   0.217843   0.547923      0.838008   0.807401    0.584833 
 0.10244    0.713315   0.366207   …  0.147993   0.942292    0.424088 
 0.720196   0.798814   0.0063958     0.462493   0.398022    0.169792 
 0.709976   0.182717   0.89811       0.697845   0.0861736   0.91016  
 ⋮                                ⋱                             

In [42]:
@time lamb, vv = eig(M)

(Complex{Float64}[49.701+0.0im,-0.859719+2.80618im,-0.859719-2.80618im,-2.74915+1.03178im,-2.74915-1.03178im,0.121286+2.73719im,0.121286-2.73719im,2.85713+0.0im,-1.96124+1.74568im,-1.96124-1.74568im  …  0.58345+0.701612im,0.58345-0.701612im,-0.296554+0.669892im,-0.296554-0.669892im,0.152363+0.766425im,0.152363-0.766425im,0.7291+0.0im,-0.231498+0.429732im,-0.231498-0.429732im,-0.21801+0.0im],
100x100 Array{Complex{Float64},2}:
 -0.0958905+0.0im   -0.011006+0.000879971im  …    0.0822483+0.0im
 -0.0915043+0.0im    0.126051-0.0153475im         0.0121654+0.0im
  -0.100584+0.0im  -0.0468398+0.00335504im      -0.00861666+0.0im
  -0.103628+0.0im   -0.132166+0.0516289im           0.13413+0.0im
  -0.107549+0.0im  -0.0368467+0.0924351im          0.106635+0.0im
  -0.110298+0.0im   0.0220754+0.031356im     …    0.0742793+0.0im
  -0.100696+0.0im    0.160927-0.0321456im         0.0851815+0.0im
 -0.0999685+0.0im  -0.0386907-0.000216099im       -0.106434+0.0im
 -0.0948583+0.0im  -0.0944342-0.0178288im 

In [43]:
lu(M)

(
100x100 Array{Float64,2}:
 1.0        0.0           0.0        …   0.0        0.0        0.0
 0.136277   1.0           0.0            0.0        0.0        0.0
 0.225522  -0.0173393     1.0            0.0        0.0        0.0
 0.998833  -0.246152     -0.362372       0.0        0.0        0.0
 0.566393   0.841798      0.358908       0.0        0.0        0.0
 0.394518   0.0838154     0.147972   …   0.0        0.0        0.0
 0.942467   0.794178     -0.757383       0.0        0.0        0.0
 0.333998   0.91536       0.478842       0.0        0.0        0.0
 0.978236   0.111627     -0.582108       0.0        0.0        0.0
 0.118411   0.780802     -0.0447548      0.0        0.0        0.0
 0.777376   0.431475     -0.60648    …   0.0        0.0        0.0
 0.920449   0.729353     -0.852392       0.0        0.0        0.0
 0.941963   0.781237     -0.166392       0.0        0.0        0.0
 ⋮                                   ⋱                            
 0.683711   0.0733574     0.523892

In [44]:
norm(M)

49.85545691676682

In [45]:
function normakvadrata(M)
    norm(M^2)
end

normakvadrata (generic function with 1 method)

In [46]:
normakvadrata(M)

2478.0012881396424

In [55]:
+(s1::String, s2::String) = string(s1, s2)

+ (generic function with 143 methods)

In [56]:
"Prvi" + " drugi"

"Prvi drugi"

In [57]:
"Vrijednost od x je " + 3

LoadError: `+` has no method matching +(::ASCIIString, ::Int64)
while loading In[57], in expression starting on line 1

In [58]:
+(s::String, x::Number) = s + "$(2x)"

+ (generic function with 144 methods)

In [59]:
"Vrijednost od x je " + 3

"Vrijednost od x je 6"

In [60]:
immutable Vector2D
    x::Float64
    y::Float64
end

In [61]:
v = Vector2D(3, 4);
w = Vector2D(5, 6);

In [62]:
v + w

LoadError: `+` has no method matching +(::Vector2D, ::Vector2D)
while loading In[62], in expression starting on line 1

In [63]:
+(v::Vector2D, w::Vector2D) = Vector2D(v.x+w.x, v.y+w.y)

+ (generic function with 145 methods)

In [64]:
v+w

Vector2D(8.0,10.0)

In [65]:
*(v::Vector2D, α::Number) = Vector2D(v.x*α, v.y*α)
*(α::Number, v::Vector2D) = Vector2D(v.x*α, v.y*α)

* (generic function with 127 methods)

In [66]:
v * 3.5

Vector2D(10.5,14.0)

In [67]:
3.5 * v

Vector2D(10.5,14.0)

In [68]:
methods(+)

# 145 methods for generic function "+":
+(x::Bool) at bool.jl:36
+(x::Bool,y::Bool) at bool.jl:39
+(y::FloatingPoint,x::Bool) at bool.jl:49
+(A::BitArray{N},B::BitArray{N}) at bitarray.jl:848
+(A::Union(DenseArray{Bool,N},SubArray{Bool,N,A<:DenseArray{T,N},I<:(Union(Int64,Range{Int64})...,)}),B::Union(DenseArray{Bool,N},SubArray{Bool,N,A<:DenseArray{T,N},I<:(Union(Int64,Range{Int64})...,)})) at array.jl:801
+{S,T}(A::Union(SubArray{S,N,A<:DenseArray{T,N},I<:(Union(Int64,Range{Int64})...,)},DenseArray{S,N}),B::Union(DenseArray{T,N},SubArray{T,N,A<:DenseArray{T,N},I<:(Union(Int64,Range{Int64})...,)})) at array.jl:723
+{T<:Union(Int32,Int16,Int8)}(x::T<:Union(Int32,Int16,Int8),y::T<:Union(Int32,Int16,Int8)) at int.jl:16
+{T<:Union(Uint16,Uint32,Uint8)}(x::T<:Union(Uint16,Uint32,Uint8),y::T<:Union(Uint16,Uint32,Uint8)) at int.jl:20
+(x::Int64,y::Int64) at int.jl:33
+(x::Uint64,y::Uint64) at int.jl:34
+(x::Int128,y::Int128) at int.jl:35
+(x::Uint128,y::Uint128) at int.jl:36
+(x::Float32,y::Float32) at float.jl:119
+(x::Float64,y::Float64) at float.jl:120
+(z::Complex{T<:Real},w::Complex{T<:Real}) at complex.jl:110
+(x::Real,z::Complex{T<:Real}) at complex.jl:120
+(z::Complex{T<:Real},x::Real) at complex.jl:121
+(x::Rational{T<:Integer},y::Rational{T<:Integer}) at rational.jl:113
+(x::Char,y::Char) at char.jl:23
+(x::Char,y::Integer) at char.jl:26
+(x::Integer,y::Char) at char.jl:27
+(a::Float16,b::Float16) at float16.jl:132
+(x::BigInt,y::BigInt) at gmp.jl:195
+(a::BigInt,b::BigInt,c::BigInt) at gmp.jl:218
+(a::BigInt,b::BigInt,c::BigInt,d::BigInt) at gmp.jl:224
+(a::BigInt,b::BigInt,c::BigInt,d::BigInt,e::BigInt) at gmp.jl:231
+(x::BigInt,c::Union(Uint16,Uint32,Uint8,Uint64)) at gmp.jl:243
+(c::Union(Uint16,Uint32,Uint8,Uint64),x::BigInt) at gmp.jl:247
+(x::BigInt,c::Union(Int64,Int32,Int16,Int8)) at gmp.jl:259
+(c::Union(Int64,Int32,Int16,Int8),x::BigInt) at gmp.jl:260
+(x::BigFloat,y::BigFloat) at mpfr.jl:149
+(x::BigFloat,c::Union(Uint16,Uint32,Uint8,Uint64)) at mpfr.jl:156
+(c::Union(Uint16,Uint32,Uint8,Uint64),x::BigFloat) at mpfr.jl:160
+(x::BigFloat,c::Union(Int64,Int32,Int16,Int8)) at mpfr.jl:164
+(c::Union(Int64,Int32,Int16,Int8),x::BigFloat) at mpfr.jl:168
+(x::BigFloat,c::Union(Float64,Float32,Float16)) at mpfr.jl:172
+(c::Union(Float64,Float32,Float16),x::BigFloat) at mpfr.jl:176
+(x::BigFloat,c::BigInt) at mpfr.jl:180
+(c::BigInt,x::BigFloat) at mpfr.jl:184
+(a::BigFloat,b::BigFloat,c::BigFloat) at mpfr.jl:255
+(a::BigFloat,b::BigFloat,c::BigFloat,d::BigFloat) at mpfr.jl:261
+(a::BigFloat,b::BigFloat,c::BigFloat,d::BigFloat,e::BigFloat) at mpfr.jl:268
+(x::MathConst{sym},y::MathConst{sym}) at constants.jl:23
+{f}(x::Fixed32{f},y::Fixed32{f}) at /projects/8e820e8f-ade8-415c-9a08-74ad6baaa8fe/.julia/v0.3/FixedPointNumbers/src/fixed32.jl:30
+{T,f}(x::UfixedBase{T,f},y::UfixedBase{T,f}) at /projects/8e820e8f-ade8-415c-9a08-74ad6baaa8fe/.julia/v0.3/FixedPointNumbers/src/ufixed.jl:85
+{T<:Number}(x::T<:Number,y::T<:Number) at promotion.jl:188
+{T<:FloatingPoint}(x::Bool,y::T<:FloatingPoint) at bool.jl:46
+(x::Number,y::Number) at promotion.jl:158
+(x::Integer,y::Ptr{T}) at pointer.jl:68
+(x::Bool,A::AbstractArray{Bool,N}) at array.jl:771
+{P<:Period}(x::Real,y::P<:Period) at /projects/8e820e8f-ade8-415c-9a08-74ad6baaa8fe/.julia/v0.3/Dates/src/dates/periods.jl:58
+(x::Number) at operators.jl:71
+(r1::OrdinalRange{T,S},r2::OrdinalRange{T,S}) at operators.jl:325
+{T<:FloatingPoint}(r1::FloatRange{T<:FloatingPoint},r2::FloatRange{T<:FloatingPoint}) at operators.jl:331
+(r1::FloatRange{T<:FloatingPoint},r2::FloatRange{T<:FloatingPoint}) at operators.jl:348
+(r1::FloatRange{T<:FloatingPoint},r2::OrdinalRange{T,S}) at operators.jl:349
+(r1::OrdinalRange{T,S},r2::FloatRange{T<:FloatingPoint}) at operators.jl:350
+(x::Ptr{T},y::Integer) at pointer.jl:66
+{S,T<:Real}(A::Union(SubArray{S,N,A<:DenseArray{T,N},I<:(Union(Int64,Range{Int64})...,)},DenseArray{S,N}),B::Range{T<:Real}) at array.jl:731
+{S<:Real,T}(A::Range{S<:Real},B::Union(

In [69]:
function sum1(N::Int)
    total = 0
    
    for i in 1:N
        total += i/2
    end
    
    total
end

function sum2(N::Int)
    total = 0.0
    
    for i in 1:N
        total += i/2
    end
    
    total
end

sum2 (generic function with 1 method)

In [70]:
sum1(10), sum2(10)

(27.5,27.5)

In [71]:
N = 10000000

@time sum1(N)
@time sum2(N)

elapsed time: 0.972562322 seconds (320003184 bytes allocated, 51.30% gc time)
elapsed time: 0.014834619 seconds (96 bytes allocated)


2.50000025e13

In [72]:
code_typed(sum2, (Int,))

1-element Array{Any,1}:
 :($(Expr(:lambda, {:N}, {{:total,symbol("#s233"),symbol("#s232"),symbol("#s231"),:i,:_var0,:_var1},{{:N,Int64,0},{:total,Float64,2},{symbol("#s233"),UnitRange{Int64},18},{symbol("#s232"),Int64,2},{symbol("#s231"),(Int64,Int64),18},{:i,Int64,18},{:_var0,Int64,18},{:_var1,Int64,18}},{}}, :(begin  # In[69], line 12:
        total = 0.0 # line 14:
        #s233 = $(Expr(:new, UnitRange{Int64}, 1, :(((top(getfield))(Intrinsics,:select_value))((top(sle_int))(1,N::Int64)::Bool,N::Int64,(top(box))(Int64,(top(sub_int))(1,1))::Int64)::Int64)))::UnitRange{Int64}
        #s232 = (top(getfield))(#s233::UnitRange{Int64},:start)::Int64
        unless (top(box))(Bool,(top(not_int))(#s232::Int64 === (top(box))(Int64,(top(add_int))((top(getfield))(#s233::UnitRange{Int64},:stop)::Int64,1))::Int64::Bool))::Bool goto 1
        2: 
        _var0 = #s232::Int64
        _var1 = (top(box))(Int64,(top(add_int))(#s232::Int64,1))::Int64
        i = _var0::Int64
        #s232 = _var1::Int6

In [73]:
code_llvm(sum2, (Int, ))


define double @julia_sum2_22795(i64) {
top:
  %1 = icmp sgt i64 %0, 0, !dbg !9355
  br i1 %1, label %L, label %L3, !dbg !9355

L:                                                ; preds = %top, %L
  %total.0 = phi double [ %5, %L ], [ 0.000000e+00, %top ]
  %"#s232.0" = phi i64 [ %2, %L ], [ 1, %top ]
  %2 = add i64 %"#s232.0", 1, !dbg !9355
  %3 = sitofp i64 %"#s232.0" to double, !dbg !9356
  %4 = fmul double %3, 5.000000e-01, !dbg !9356
  %5 = fadd double %total.0, %4, !dbg !9356
  %6 = icmp eq i64 %"#s232.0", %0, !dbg !9356
  br i1 %6, label %L3, label %L, !dbg !9356

L3:                                               ; preds = %L, %top
  %total.1 = phi double [ 0.000000e+00, %top ], [ %5, %L ]
  ret double %total.1, !dbg !9357
}


In [74]:
code_native(sum2, (Int,))

	.text
Filename: In[69]
Source line: 15
	push	RBP
	mov	RBP, RSP
	xorps	XMM0, XMM0
	test	RDI, RDI
	jle	47
	mov	EAX, 1
	movabs	RCX, 140481969459824
	movsd	XMM1, QWORD PTR [RCX]
Source line: 15
	xorps	XMM2, XMM2
	cvtsi2sd	XMM2, RAX
	mulsd	XMM2, XMM1
	addsd	XMM0, XMM2
Source line: 14
	inc	RAX
Source line: 15
	dec	RDI
	jne	-28
Source line: 18
	pop	RBP
	ret


In [75]:
#instalirao sam s Pkg.add("PyCall")
using PyCall

In [76]:
@pyimport numpy.random as nprandom
nprandom.rand(3,4)

3x4 Array{Float64,2}:
 0.204852  0.0548087  0.664496  0.753985
 0.920138  0.3342     0.88458   0.830015
 0.769597  0.483396   0.4446    0.495534

In [77]:
objective = x -> cos(x) - x #ekvivalent lambda funkcijama u Pythonu

(anonymous function)

In [78]:
@pyimport scipy.optimize as so
so.newton(objective, 1)

0.7390851332151607

In [79]:
t = ccall( (:clock, "libc"), Int32, ())

52404180

In [80]:
help("ccall")

Base.ccall((symbol, library) or fptr, RetType, (ArgType1, ...), ArgVar1, ...)

   Call function in C-exported shared library, specified by
   "(function name, library)" tuple, where each component is a
   String or :Symbol. Alternatively, ccall may be used to call a
   function pointer returned by dlsym, but note that this usage is
   generally discouraged to facilitate future static compilation. Note
   that the argument type tuple must be a literal tuple, and not a
   tuple-valued variable or expression.


In [81]:
function es(n::Int64)
    l = ones(Bool, n)
    l[1] = false
    for i in 2:int64(sqrt(n))
        if l[i]
            for j in (i*i):i:n
                l[j] = false
            end
        end
    end
    return filter(x -> l[x],1:n)
end

es (generic function with 1 method)